# Generated by Django 4.2.3 on 2023-07-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='PressService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroka', models.TextField()),
            ],
            options={
                'verbose_name': 'Пресс-служба',
                'verbose_name_plural': 'Пресс-службы',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='fontawesome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
