# Generated by Django 4.2.3 on 2023-07-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_contacts_pressservice_settings_fontawesome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PressService',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='fontawesome',
        ),
        migrations.AddField(
            model_name='contacts',
            name='fontawesome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
