# Generated by Django 4.2.3 on 2023-07-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_delete_pressservice_remove_settings_fontawesome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='press_service',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='selection_committee',
        ),
    ]
