# Generated by Django 4.2.3 on 2023-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news_image')),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ОБЪЯВЛЕНИЕ',
                'verbose_name_plural': 'ОБЪЯВЛЕНИЯ',
            },
        ),
    ]
