# Generated by Django 4.2.3 on 2023-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='video')),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(upload_to='announcement_image'),
        ),
    ]
