# Generated by Django 4.2.3 on 2023-07-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_appeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='descriprion',
            new_name='description',
        ),
    ]
