# Generated by Django 4.2.3 on 2023-07-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_rename_descriprion_appeal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
